server:
  port: 8087
  servlet:
    context-path: /car_dealership

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
#    Work
#    url: jdbc:postgresql://192.168.200.199:5432/pietakiewicz
#    username: pietakiewicz_usr
#    password: pietakiewicz@pg$ql8
#    Home
    url: jdbc:postgresql://localhost:5432/car_dealership
    username: postgres
    password: postgres
    hikari:
      idle-timeout: 10000
      connectionTimeout: 20000
      minimumIdle: 10
      maximumPoolSize: 20
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG